import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { useRouter } from "next/router";
import BusinessCard from "~/components/BusinessCard/BusinessCard";
import { useState } from "react";
import { type } from './../utils/api';

const Home: NextPage = () => {
  const [inputs, setInputs] = useState({
    title: "",
    website: "",
  });

  const { data: sessionData } = useSession();

  const router = useRouter()

  return (
    <>
      <Head>
        <title>Business Card App - T3 stack</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-[calc(100vh-4rem)] flex-col items-center justify-center bg-gradient-to-br from-rose-500 to-purple-600">
        {!sessionData && (
          <button
            // eslint-disable-next-line @typescript-eslint/no-misused-promises
            onClick={sessionData ? () => signOut() : () => signIn('google')}
            className='rounded-full bg-black/10 px-10 py-3 font-semibold text-black no-underline transition hover:bg-black/20'>
            Sign in with Google
          </button>
        )}

        {/* Tell us about yourself */}
        <div className="mx-auto max-w-7xl">
          <h2 className="">Tell us about yourself</h2>
          <div className="mb-12 grid-cols-2 gap-8">
            {/* Input field 1 */}
            <div>
              <label className="">
                Title
              </label>
              <div className="mt-1">
                <input
                  value={inputs.title}
                  type="text"
                  name="title"
                  className="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:border-ring-indigo-500"
                  placeholder="Software Engineer"
                />
              </div>
            </div>

            {/* Input field 2 */}
            <div>
              <label htmlFor="email" className="block text-sm font-sm font-medium text-white">
                Website
              </label>
              <div className="mt-1">
                <input
                  value={inputs.website}
                  type="text"
                  name="website"
                  className="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                  placeholder="yourself.com"
                />
              </div>
            </div>
          </div>
        </div>

        {/* Main Business card */}
        {sessionData && (
          <div className="flex flex-col items-center justify-center">
            <BusinessCard />
          </div>
        )}

      </div>

    </>
  );
};

export default Home;

