import { type NextPage } from "next";
import { useState, Fragment } from "react";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import BusinessCard from "~/components/BusinessCard/BusinessCard";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  const [inputs, setInputs] = useState({
    title: "",
    website: "",
  });

  const publish = () => console.log('publish')

  return (
    <Fragment>
      <Head>
        <title>Business Card App - T3 stack</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-[calc(100vh-4rem)] flex-col items-center justify-center bg-gradient-to-br from-rose-500 to-purple-600">
        {!sessionData && (
          <button
            // eslint-disable-next-line @typescript-eslint/no-misused-promises
            onClick={sessionData ? () => signOut() : () => signIn('google')}
            className='rounded-full bg-black/10 px-10 py-3 font-semibold text-black no-underline transition hover:bg-black/20'>
            Sign in with Google
          </button>
        )}

        {/* Main Business card */}
        {sessionData && (
          <Fragment>
            {/* Tell us about yourself */}
            <div className="mx-auto max-w-7xl">
              <h2 className="mb-6 text-left text-3xl font-semibold text-white">Tell us about yourself</h2>
              <div className="mb-12 grid-cols-2 gap-8">
                {/* Input field 1 */}
                <div>
                  <label htmlFor="email" className="block text-sm font-medium text-white">
                    Title
                  </label>
                  <div className="mt-1">
                    <input
                      value={inputs.title}
                      onChange={(e) => setInputs(prev => ({ ...prev, title: e.target.value }))}
                      type="text"
                      name="title"
                      className="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                      placeholder="Software Engineer"
                    />
                  </div>
                </div>

                {/* Input field 2 */}
                <div>
                  <label htmlFor="email" className="block text-sm font-medium text-white">
                    Website
                  </label>
                  <div className="mt-1">
                    <input
                      value={inputs.website}
                      type="text"
                      name="website"
                      onChange={(e) => setInputs(prev => ({ ...prev, website: e.target.value }))}
                      className="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                      placeholder="yourself.com"
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* Main BusinessCard */}
            <div className="flex flex-col items-center justify-center">
              <BusinessCard inputs={inputs} />
            </div>

            {/* Publish Button */}
            <div className="mt-12 flex justify-center">
              <button
                onClick={publish}
                type="button"
                className="rounded-full bg-black/10 px-10 font-semibold text-white no-underline transition hover:bg-black/20"
              >
                Publish
              </button>
            </div>
          </Fragment>
        )}
      </div>
    </Fragment>
  );
};

export default Home;

